# Variables
DEVRAIL_IMAGE ?= ghcr.io/devrail-dev/dev-toolchain:v1
DOCKER_RUN    ?= docker run --rm -v "$$(pwd):/workspace" -w /workspace $(DEVRAIL_IMAGE)
HUGO_VERSION  ?= latest

.DEFAULT_GOAL := help

# .PHONY declarations
.PHONY: help build serve lint format test security scan docs check install-hooks
.PHONY: _lint _format _test _security _scan _docs _check

# Public targets
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

build: ## Build the Hugo site
	hugo --minify

serve: ## Start local Hugo development server
	hugo server --buildDrafts --buildFuture

lint: ## Run all linters
	$(DOCKER_RUN) make _lint

format: ## Run all formatters
	$(DOCKER_RUN) make _format

test: ## Run all tests
	$(DOCKER_RUN) make _test

security: ## Run security scanners
	$(DOCKER_RUN) make _security

scan: ## Run full scan (lint + security)
	$(DOCKER_RUN) make _scan

docs: ## Generate documentation
	$(DOCKER_RUN) make _docs

check: ## Run all checks (lint, format, test, security, docs)
	$(DOCKER_RUN) make _check

install-hooks: ## Install pre-commit hooks
	pre-commit install

# Internal targets
_lint:
	@echo "lint: no language-specific linters for documentation site"

_format:
	@echo "format: no language-specific formatters for documentation site"

_test:
	@echo "test: no language-specific tests for documentation site"

_security:
	@echo "security: no language-specific security scanners for documentation site"

_scan:
	@echo "scan: universal scanners not yet configured"

_docs:
	@echo "docs: documentation is generated by Hugo build target"

_check: _lint _format _test _security _scan _docs
	@echo "check: all checks complete"
